name: Build & Release Extensions

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Package Chrome extension
        run: zip -r chrome-extension-${{ github.ref_name }}.zip chrome

      - name: Package Firefox extension
        run: zip -r firefox-extension-${{ github.ref_name }}.xpi firefox

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Chrome asset
        uses: softprops/action-gh-release@v2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: chrome-extension-${{ github.ref_name }}.zip
          asset_name: chrome-extension-${{ github.ref_name }}.zip
          asset_content_type: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Firefox asset
        uses: softprops/action-gh-release@v2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: firefox-extension-${{ github.ref_name }}.xpi
          asset_name: firefox-extension-${{ github.ref_name }}.xpi
          asset_content_type: application/x-xpinstall
          token: ${{ secrets.GITHUB_TOKEN }}
